### ISSUE TITLE
Pip install issues Python 2.7

### ISSUE THREAD

**Issue by Auha** [StellarCN/py-stellar-base#163]
I get the following error message when install from pip with Python 2.7

`Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/g_/2bn3zl1x7qvbphs25lx7s1rh0000gn/T/pip-install-RTccCh/stellar-base/setup.py", line 9, in <module>
        with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function`

I am able to install it correctly on Python 3.6, but my current code base isn't python 3.x compatible at the moment. 

After doing some quick research, I am able to install the stellar-base correctly when cloning the repo and installing from source. I tried out 1.9 tag, 

I downloaded and unzipped the tarball from pypi, and I had the above problem.

**Comment by Auha** [comment]
So I cloned the repo over, and everything seems to work properly from installing from the repo. I'll do an investigation from the pkg I get from pypi.

**Comment by overcat** [comment]
Sorry for that, please try to install using `pip install stellar-sdk`.

**Comment by Auha** [comment]
Can you change the documentation for that? Or would you want a pull request?

**Comment by overcat** [comment]
I will do it later.

Jonathan Chen <notifications@github.com> 于 2018年10月24日周三 11:41写道：

**Comment by overcat** [comment]
b8e1a518419e5985fafb58e66c280ab15c515976

**Comment by Auha** [comment]
So I am having issues still with installing stellar-sdk from pypi. I get the following stack trace. 

`Exception:
Traceback (most recent call last):
  File "/Users/tamasiaina/.virtualenvs/stellar1/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/Users/tamasiaina/.virtualenvs/stellar1/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 366, in run
    use_user_site=options.use_user_site,
  File "/Users/tamasiaina/.virtualenvs/stellar1/lib/python2.7/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/Users/tamasiaina/.virtualenvs/stellar1/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 760, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/Users/tamasiaina/.virtualenvs/stellar1/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 382, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/Users/tamasiaina/.virtualenvs/stellar1/lib/python2.7/site-packages/pip/_internal/wheel.py", line 326, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: stellar-sdk .dist-info directory not found`

Its better than before as I am "still" able to use it, BUT its kind of not good to have some sort of error while installing.

**Comment by overcat** [comment]
Hi, @Auha 
I will check tomorrow why it was broken in 0.2.2, I will tell you after i fix it, thank you for your feedback. In addition, 0.2.1 will not have this error.
`pip install stellar-sdk==0.2.1`

**Comment by petermuller71** [comment]
And I get install errors too:

Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-Kkv1c7/ed25519/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-k8LAxf/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-Kkv1c7/ed25519/
