### ISSUE TITLE
cannot create envelope from xdr that has SetOptions op with "Signer Public Key"

### ISSUE THREAD

**Issue by Akuukis** [StellarCN/py-stellar-base#39]
``` python
# tx with SetOptions that has "Signer Public Key" and "Signer Weight" set  
tx_b64="AAAAAICWoainP1dIvO1xv/MPunWGvb3MOnUB3AFsbH7KKehEAAAAZAAazYAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAUAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAJyo6y9g/yze+SB68uAT/mWOGOSHYA64F4Po0qZeOjXRAAAAAwAAAAAAAAAA"

envelope = Te.from_xdr(tx_b64) # crashes here as below without changes in stellar_base/operations.py
envelope.sign(keypair=Keypair.from_seed(seed=seed)) # crashes here with changes in stellar_base/operations.py
```

```
----------------------------------------
Traceback (most recent call last):
  ...
    envelope = Te.from_xdr(tx_b64)
  File "/home/$USER/git/sr/py-stellar-base/stellar_base/transaction_envelope.py", line 62, in from_xdr
    tx = Transaction.from_xdr_object(tx_xdr_object)
  File "/home/$USER/git/sr/py-stellar-base/stellar_base/transaction.py", line 81, in from_xdr_object
    operations.append(SetOptions.from_xdr_object(op))
  File "/home/$USER/git/sr/py-stellar-base/stellar_base/operation.py", line 331, in from_xdr_object
    signer_address = op_xdr_object.body.setOptionsOp.signer.pubKey.ed25519
AttributeError: 'list' object has no attribute 'pubKey'
----------------------------------------
```

If I change these lines in `stellar_base/operations.py` lines 329-332

``` python
# Old version
        if op_xdr_object.body.setOptionsOp.signer:
            signer_address = op_xdr_object.body.setOptionsOp.signer.pubKey.ed25519
            signer_weight = op_xdr_object.body.setOptionsOp.signer.weight
# New version
        if op_xdr_object.body.setOptionsOp.signer:
            signer_address = op_xdr_object.body.setOptionsOp.signer[0].pubKey.ed25519
            signer_weight = op_xdr_object.body.setOptionsOp.signer[0].weight
```

then tx is made without errors but throws this error while trying to sign

```
----------------------------------------
Traceback (most recent call last):
  File "/home/$USER/git/sr/py-stellar-base/stellar_base/utils.py", line 94, in decode_check
    decoded = base64.b32decode(encoded)
  File "/usr/lib/python3.4/base64.py", line 236, in b32decode
    raise binascii.Error('Non-base32 digit found') from None
binascii.Error: Non-base32 digit found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  ...
    envelope.sign(keypair=Keypair.from_seed(seed=seed))
  File "/home/$USER/git/sr/py-stellar-base/stellar_base/transaction_envelope.py", line 22, in sign
    tx_hash = self.hash_meta()
  File "/home/$USER/git/sr/py-stellar-base/stellar_base/transaction_envelope.py", line 31, in hash_meta
    return xdr_hash(self.signature_base())
  File "/home/$USER/git/sr/py-stellar-base/stellar_base/transaction_envelope.py", line 40, in signature_base
    tx.pack_Transaction(self.tx.to_xdr_object())
  File "/home/$USER/git/sr/py-stellar-base/stellar_base/transaction.py", line 40, in to_xdr_object
    operations = [o.to_xdr_object() for o in self.operations]
  File "/home/$USER/git/sr/py-stellar-base/stellar_base/transaction.py", line 40, in <listcomp>
    operations = [o.to_xdr_object() for o in self.operations]
  File "/home/$USER/git/sr/py-stellar-base/stellar_base/operation.py", line 299, in to_xdr_object
    signer = [Xdr.types.Signer(account_xdr_object(self.signer_address), self.signer_weight)]
  File "/home/$USER/git/sr/py-stellar-base/stellar_base/utils.py", line 42, in account_xdr_object
    public_key = decode_check('account', account)
  File "/home/$USER/git/sr/py-stellar-base/stellar_base/utils.py", line 96, in decode_check
    raise DecodeError('Incorrect padding')
stellar_base.utils.DecodeError: Incorrect padding
----------------------------------------
```

I am using last commit a4930eba7c2926740a913142c031f548af356b44 in master branch

**Comment by Akuukis** [comment]
e7215ac5ef8ef7a86dc154af764c9a92879adce9 seems to fix it. Is that the correct way to handle this?

**Comment by Akuukis** [comment]
No, e7215ac works but does something wrong, because signature on it is not valid to submit to Stellar Network.

**Comment by manran** [comment]
i have tested e7215ac5ef8ef7a86dc154af764c9a92879adce9 ,and it works . 
Were you try on the livenet? now the Te.from_xdr() have no idea about which network the xdr using, and give the testnet as the network .
maybe i need write a wrapper for this method, to load xdr from livenet /testnet or other network?

**Comment by Akuukis** [comment]
Thanks for looking into it! Oh sorry, I tried again and found a problem in my test, in fact e7215ac does work also for me. I was using tx above and used old seed that is not eligible to sign such op thus got `bad_auth` and misinterpreted it as broken signature.
