### ISSUE TITLE
manageData op sees data_name as 3 chars longer

### ISSUE THREAD

**Issue by Akuukis** [StellarCN/py-stellar-base#40]
When I pass 64 character long utf-8 string as `data_name` to `manageData` I get error below. 

```
----------------------------------------
Traceback (most recent call last):
  ...
    envelope.sign(keypair=Keypair.from_seed(seed=seed))
  File "/home/kalvis/git/sr/py-stellar-base/stellar_base/transaction_envelope.py", line 22, in sign
    tx_hash = self.hash_meta()
  File "/home/kalvis/git/sr/py-stellar-base/stellar_base/transaction_envelope.py", line 31, in hash_meta
    return xdr_hash(self.signature_base())
  File "/home/kalvis/git/sr/py-stellar-base/stellar_base/transaction_envelope.py", line 40, in signature_base
    tx.pack_Transaction(self.tx.to_xdr_object())
  File "/home/kalvis/git/sr/py-stellar-base/stellar_base/stellarxdr/StellarXDR_pack.py", line 728, in pack_Transaction
    self.pack_array(data.operations, self.pack_Operation)
  File "/usr/lib/python3.4/xdrlib.py", line 111, in pack_array
    self.pack_farray(n, list, pack_item)
  File "/usr/lib/python3.4/xdrlib.py", line 106, in pack_farray
    pack_item(item)
  File "/home/kalvis/git/sr/py-stellar-base/stellar_base/stellarxdr/StellarXDR_pack.py", line 654, in pack_Operation
    self.pack_ManageDataOp(data.body.manageDataOp)
  File "/home/kalvis/git/sr/py-stellar-base/stellar_base/stellarxdr/StellarXDR_pack.py", line 593, in pack_ManageDataOp
    self.pack_string64(data.dataName)
  File "/home/kalvis/git/sr/py-stellar-base/stellar_base/stellarxdr/StellarXDR_pack.py", line 128, in pack_string64
    raise XDRError('array length too long for data')
xdrlib.Error: array length too long for data
----------------------------------------
```

Adding debug line `print(len(data))` in `StellarXDR_pack.py` line 127 I learn that at that point string is seen as 67 bytes long and wraps byte string within another byte string like this:

```
bytearray(b"b\'my64charLongString__________xxxxxxxxxx___________xxxxxxxxxxx____\'")
```

**Comment by manran** [comment]
```python3
>>> data_name =  'my64charLongString__________xxxxxxxxxx___________xxxxxxxxxxx____'
>>> data_value = 'test'
>>> builder = Builder('SCVLSUGYEAUC4MVWJORB63JBMY2CEX6ATTJ5MXTENGD3IELUQF4F6HUB')
>>> builder.append_manage_data_op(data_name,data_value)
>>> builder.gen_xdr()
b'AAAAAOo1QK/3upA74NLkdq4Io3DQAQZPi4TVhuDnvCYQTKIVAAAAZAAUhoEAAAAFAAAAAAAAAAAAAAABAAAAAAAAAAoAAABAbXk2NGNoYXJMb25nU3RyaW5nX19fX19f
X19fX3h4eHh4eHh4eHhfX19fX19fX19fX3h4eHh4eHh4eHh4X19fXwAAAAEAAAAEdGVzdAAAAAAAAAABEEyiFQAAAECoF7fVysCdv7wEICV5NT4beKjBkWke5EmmiwItic
9dAt0nJD5Fb4x0+w9DzD7L4oTL6jFI3j6WMG1aqGVvBV4D'
```
python 3.5 on Windows. weird.

**Comment by manran** [comment]
```python3
>>> data_name =  'my64charLongString__________xxxxxxxxxx___________xxxxxxxxxxx____'
>>> data_value = 'test'
>>> builder = Builder('SCVLSUGYEAUC4MVWJORB63JBMY2CEX6ATTJ5MXTENGD3IELUQF4F6HUB')
>>> builder.append_manage_data_op(data_name,data_value)
>>> builder.gen_xdr()
b'AAAAAOo1QK/3upA74NLkdq4Io3DQAQZPi4TVhuDnvCYQTKIVAAAAZAAUhoEAAAAFAAAAAAAAAAAAAAABAAAAAAAAAAoAAABAbXk2NGNoYXJMb25nU3RyaW5nX19fX19f
X19fX3h4eHh4eHh4eHhfX19fX19fX19fX3h4eHh4eHh4eHh4X19fXwAAAAEAAAAEdGVzdAAAAAAAAAABEEyiFQAAAECoF7fVysCdv7wEICV5NT4beKjBkWke5EmmiwItic
9dAt0nJD5Fb4x0+w9DzD7L4oTL6jFI3j6WMG1aqGVvBV4D'
```
python 3.5 on Windows. weird.

**Comment by Akuukis** [comment]
Debian 8 with Python3.4.2 - behavior as above
Debian 8 with Python3.5.2 - behavior as above

**Comment by Akuukis** [comment]
864b23cf0f4ca359f95d74286ea5de179aff8b92 has fixed this on Debian 8 with Python3.4.2 and Python3.5.2.

**Comment by manran** [comment]
sorry my bad. i have fixed it on the master branch , but didn't push.

**Comment by Akuukis** [comment]
Oh, ok. Will you add test as above or should I do it later?

**Comment by manran** [comment]
I will write tests for this . Thank you !
