### ISSUE TITLE
Getting error when run python3 create_account.py "Resource Missing'

### ISSUE THREAD

**Issue by vikujangid** [StellarCN/py-stellar-base#593]
`python3 create_account.py `

```
Traceback (most recent call last):
  File "create_account.py", line 13, in <module>
    source_account = server.load_account(account_id=source.public_key)
  File "/Users/vikasjerthi/Library/Python/3.8/lib/python/site-packages/typeguard/__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "/Users/vikasjerthi/Library/Python/3.8/lib/python/site-packages/stellar_sdk/server.py", line 109, in load_account
    resp = self.accounts().account_id(account_id=account_id.account_id).call()
  File "/Users/vikasjerthi/Library/Python/3.8/lib/python/site-packages/typeguard/__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "/Users/vikasjerthi/Library/Python/3.8/lib/python/site-packages/stellar_sdk/call_builder/call_builder_sync/base_call_builder.py", line 43, in call
    return self._call(url, self.params)
  File "/Users/vikasjerthi/Library/Python/3.8/lib/python/site-packages/typeguard/__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "/Users/vikasjerthi/Library/Python/3.8/lib/python/site-packages/stellar_sdk/call_builder/call_builder_sync/base_call_builder.py", line 48, in _call
    raise_request_exception(raw_resp)
  File "/Users/vikasjerthi/Library/Python/3.8/lib/python/site-packages/typeguard/__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "/Users/vikasjerthi/Library/Python/3.8/lib/python/site-packages/stellar_sdk/exceptions.py", line 181, in raise_request_exception
    raise NotFoundError(response)
stellar_sdk.exceptions.NotFoundError: {
  "type": "https://stellar.org/horizon-errors/not_found",
  "title": "Resource Missing",
  "status": 404,
  "detail": "The resource at the url requested was not found.  This usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided."
}
```

**Comment by overcat** [comment]
You need to fund the source account first, please check https://developers.stellar.org/docs/tutorials/create-account/

**Comment by vikujangid** [comment]
@overcat thank you for reply :)
I funded but same error

**Comment by overcat** [comment]
I don't think it's being funded
```python
>>> from stellar_sdk import Keypair, Network, Server, TransactionBuilder
>>>
>>> source = Keypair.from_secret("SBFZCHU5645DOKRWYBXVOXY2ELGJKFRX6VGGPRYUWHQ7PMXXJNDZFMKD")
>>> source.public_key
'GCZ2GEDRGWOB42FGJM3UVW2PQPOTKAUD5TFYUIVTJZR3ROCBJATPGB4R'
```

https://horizon-testnet.stellar.org/accounts/GCZ2GEDRGWOB42FGJM3UVW2PQPOTKAUD5TFYUIVTJZR3ROCBJATPGB4R returns 404.

you can fund it here: https://laboratory.stellar.org/#account-creator?network=test

**Comment by vikujangid** [comment]
Oh!! Sorry, my mistake. You are right.. I was looking at the wrong file.. 

Thanks Buddy
