### ISSUE TITLE
Payments Fail on Publicnet (Section 4  of Tutorial with and without builder)

### ISSUE THREAD

**Issue by Gitzman** [StellarCN/py-stellar-base#60]
Using python 2.7, most up to date code from github.  Section 4.1 from tutorial.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gitzman/anaconda3/envs/stellar/lib/python2.7/site-packages/stellar_base-0.1.0-py2.7.egg/stellar_base/builder.py", line 324, in submit
    raise e
ValueError: No JSON object could be decoded

**Comment by Gitzman** [comment]
I was wrong.  Need to create account first using section 2 to send to.  This all works.  THanks!
