### ISSUE TITLE
Having trouble recovering seed from wordlist

### ISSUE THREAD

**Issue by kfiresmith** [StellarCN/py-stellar-base#63]
Hello,
I'm having a hard time figuring out how to recover a seed from a deterministic word list.  Using the test wordlist below that was generated using the existing readme.md documentation.

```python
>>> seed_string = "orchard fan alcohol palm jaguar cool invest maple eager foster pencil cluster"
>>> seed_binary = str.encode(seed_string)
>>> kp = Keypair.from_seed(seed_binary)
Traceback (most recent call last):
  File "/home/webusr/devel/overcat_mnemonic/lib64/python3.6/site-packages/stellar_base/utils.py", line 118, in decode_check
    decoded = base64.b32decode(encoded)
  File "/usr/lib64/python3.6/base64.py", line 205, in b32decode
    raise binascii.Error('Incorrect padding')
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/webusr/devel/overcat_mnemonic/lib64/python3.6/site-packages/stellar_base/keypair.py", line 48, in from_seed
    raw_seed = decode_check("seed", seed)
  File "/home/webusr/devel/overcat_mnemonic/lib64/python3.6/site-packages/stellar_base/utils.py", line 120, in decode_check
    raise DecodeError('Incorrect padding')
stellar_base.utils.DecodeError: Incorrect padding
```

I have tried a few different things to get the string/binary conversion to be happy, and I will keep trying, but I figured if anyone around might know how to do it already, if you show me how I'll add that documentation to the readme.

Thanks!

**Comment by overcat** [comment]
The seed is like this `SCVLSUGYEAUC4MVWJORB63JBMY2CEX6ATTJ5MXTENGD3IELUQF4F6HUB`，
If you want to recovery seed from wordlist, you should do this.
```
Python 3.6.3 (default, Dec  5 2017, 22:54:32) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from stellar_base.keypair import Keypair
>>> seed_string = "orchard fan alcohol palm jaguar cool invest maple eager foster pencil cluster"
>>> kp = Keypair.deterministic(seed_string)
>>> kp.address().decode()
'GDPQMHV67HIU6UNR5NUGNUBHZL7QNATANQQGCUZKRAL5Y7GGS3RAFTQF'
```

This problem has been pointed out in the section 1 of the document, please read it carefully.

**Comment by kfiresmith** [comment]
Thanks @overcat !
Being somewhat new to the Python SDK it wasn't immediately clear to me, but with #64 merged I'm hoping it will be more immediately clear to anyone else who is unfamiliar with the code.
