### ISSUE TITLE
ImportError: No module named ed25519._ed25519

### ISSUE THREAD

**Issue by kunlegiwa** [StellarCN/py-stellar-base#69]
Hi, I tried to generate a keypair and got the error below. Could you please take a look? Thanks.
Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\runtime\wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\runtime\wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\runtime\wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "C:\Users\kunle\Documents\LAGOS_BUSINESS\ISHOPEAZYV2\iShopEazyV2WebApp\ishopeazy.py", line 21, in <module>
    from stellar_base.keypair import Keypair
  File "C:\Users\kunle\Documents\LAGOS_BUSINESS\ISHOPEAZYV2\iShopEazyV2WebApp\lib\stellar_base\keypair.py", line 7, in <module>
    from .utils import XdrLengthError, decode_check, encode_check
  File "C:\Users\kunle\Documents\LAGOS_BUSINESS\ISHOPEAZYV2\iShopEazyV2WebApp\lib\stellar_base\utils.py", line 15, in <module>
    import ed25519
  File "C:\Users\kunle\Documents\LAGOS_BUSINESS\ISHOPEAZYV2\iShopEazyV2WebApp\lib\ed25519\__init__.py", line 1, in <module>
    from .keys import (BadSignatureError, BadPrefixError,
  File "C:\Users\kunle\Documents\LAGOS_BUSINESS\ISHOPEAZYV2\iShopEazyV2WebApp\lib\ed25519\keys.py", line 3, in <module>
    from . import _ed25519
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\devappserver2\python\runtime\sandbox.py", line 1093, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named ed25519._ed25519

**Comment by kfiresmith** [comment]
I have no idea how Python works on Windows, but you need to figure out how to import the ed25519 module which is separate from this project, though this project depends on it.

https://pypi.python.org/pypi/ed25519

**Comment by kunlegiwa** [comment]
Ok, thank you for your very fast response. I tried yesterday without any luck. I will try to look for a workaround.

**Comment by kfiresmith** [comment]
No problem @kunlegiwa  - my flippant suggestion for a workaround is to start using Linux ;)
More seriously, you need to install pip on Windows (I googled and found: https://stackoverflow.com/questions/4750806/how-do-i-install-pip-on-windows), then pip install that missing ed25519 module.

**Comment by overcat** [comment]
Can you try to install ed25519 separately?  Please enter the following command in cmd:
```
pip install ed25519
python
import ed25519._ed25519
```
If this works for you, the problem may be caused by GAE, but I do not have the experience of GAE, so I can not give you more advice, you should check out the documentation of GAE.

Thanks.

**Comment by kunlegiwa** [comment]
Hi, I think you are right. It works well in poweshell, just not GAE.

**Comment by kunlegiwa** [comment]
I have gathered from stackoverflow that Ineed to find an implementation of Ed25519 that doesn't require the use of a C extension.

**Comment by kfiresmith** [comment]
Oh.  That makes sense on GAE.  That is a bummer.  I wonder if it could somehow be pre-compiled before placing on the GAE rather than built by gcc and python-devel as it would be on a VM...

**Comment by overcat** [comment]
You can try to replace ed25519 with pure25519.

https://github.com/warner/python-pure25519
