### ISSUE TITLE
Error when signing envelope with TextMemo or custom Asset

### ISSUE THREAD

**Issue by Akuukis** [StellarCN/py-stellar-base#7]
I get error `TypeError: Can't convert 'bytes' object to str implicitly` when trying to sign the envelope that has TextMemo. If using NoneMemo, everything works. See the full error and code below.
````
Account Generated: GBEB4GEO6QBM4UNNRIAODMFYFPULUQCBHCFBK4N6HMWBLX4VD7FLNAFH
Account Generated: GBD3PW4PF7I7HRLEZM5CLFDGRXG7TXZIGX64KKUF2FPRUCNHFH664KMC
Traceback (most recent call last):
  File "sample-error.py", line 68, in <module>
    envelope.sign(Keypair.from_seed(anna['seed']))
  File "src/lib/stellar-sdk-py/stellar_base/transaction_envelope.py", line 20, in sign
    tx_hash = self.hash_meta()
  File "src/lib/stellar-sdk-py/stellar_base/transaction_envelope.py", line 26, in hash_meta
    return xdr_hash(self.signature_base())
  File "src/lib/stellar-sdk-py/stellar_base/transaction_envelope.py", line 35, in signature_base
    tx.pack_Transaction(self.tx.to_xdr_object())
  File "src/lib/stellar-sdk-py/stellar_base/stellarxdr/StellarXDR_pack.py", line 1286, in pack_Transaction
    self.pack_Memo(data.memo)
  File "src/lib/stellar-sdk-py/stellar_base/stellarxdr/StellarXDR_pack.py", line 1241, in pack_Memo
    self.pack_string(data.text)
  File "/usr/local/lib/python3.5/xdrlib.py", line 108, in pack_string
    self.pack_fstring(n, s)
  File "/usr/local/lib/python3.5/xdrlib.py", line 100, in pack_fstring
    data = data + (n - len(data)) * b'\0'
TypeError: Can't convert 'bytes' object to str implicitly
````

````python
# coding:utf-8
import sys
sys.path.append('src/')
sys.path.append('src/lib/stellar-sdk-py')

from stellar_base.operation import Payment
from stellar_base.asset import Asset
from stellar_base.transaction import Transaction
from stellar_base.transaction_envelope import TransactionEnvelope as Te
from stellar_base.keypair import Keypair
from stellar_base.memo import *

url = 'https://horizon-testnet.stellar.org'

def newAccount(creator=False):
	import requests
	import simplejson as json
	from stellar_base.keypair import Keypair

	# Generate keys
	kp = Keypair.random()

	# Fund account
	if(creator=='friendbot'):
		# from Friendbot
		urlParam = url + '/friendbot?addr=' + kp.address().decode('ascii')
		r = requests.get(urlParam) # Get 1000 lumens
		assert 'hash' in json.loads(r.text), "\n" + urlParam + "\n" + r.text
	elif(creator):
		assert False, "TODO"
	else:
		# Dont fund it
		pass

	print('Account Generated: ' + kp.address().decode('ascii'))

	return {
		'address': kp.address().decode('ascii'),
		'seed': kp.seed().decode('ascii')
	}

def fetchSeq(address):
	assert address
	import requests
	import simplejson as json
	return json.loads(requests.get(url+'/accounts/'+address).text)['sequence']

def announce(envelope_b64=False):
	assert envelope_b64
	import requests
	import simplejson as json
	r = requests.post(url+'/transactions', data={'tx': envelope_b64.decode('ascii')})
	msg = json.loads(r.text)
	
	if('hash' in msg):
		print('Tx: ', msg['hash'])
	else:
		from pprintpp import pprint as pp # https://github.com/wolever/pprintpp
		print('Tx warning: ')
		pp(msg)
	return msg

def packer(envelope=False):
	assert envelope

	import base64
	from stellar_base.stellarxdr import StellarXDR_pack as Xdr
	x = Xdr.STELLARXDRPacker()
	x.pack_TransactionEnvelope(envelope.to_xdr_object())
	
	return base64.b64encode(x.get_buffer())

# base info
anna = newAccount('friendbot')
bob = newAccount('friendbot')

operation = Payment({
	'source': anna['address'],
	'destination': bob['address'],
	'asset': Asset.native(),
	'amount': 10*10**6,
})
tx = Transaction(
	source=anna['address'],
	opts={
		'seqNum': fetchSeq(anna['address']),
		'timeBounds': [],
		'memo': TextMemo('Just testing'),
		'fee': 100,
		'operations': [
			operation,
		],
	},
)
envelope = Te(tx=tx, opts={"network_id": "TESTNET"})
envelope.sign(Keypair.from_seed(anna['seed']))

announce(packer(envelope))
````

**Comment by Akuukis** [comment]
Still open for lastest commit 12a4b4b

**Comment by Akuukis** [comment]
The same happens if want to sign envelope with non-native currency.

**Comment by Akuukis** [comment]
With Python2.7 works with 4char assets, but don't with longer assets.

````
  File "src/lib/stellar-sdk-py/stellar_base/stellarxdr/StellarXDR_pack.py", line 583, in pack_Asset
    raise TypeError( 'data.alphaNum4 == None')
TypeError: data.alphaNum4 == None
````

Also with Python2.7 TextMemo doesn't work but with different error

````
    'memo': TextMemo('A'), # Broken for now.
  File "src/lib/stellar-sdk-py/stellar_base/memo.py", line 18, in __init__
    length = len(bytes(text, encoding='utf-8'))
TypeError: str() takes at most 1 argument (2 given)
````
