### ISSUE TITLE
 server.trade_aggregations.stream() not working

### ISSUE THREAD

**Issue by AnimusXCASH** [StellarCN/py-stellar-base#876]
Hey @overcat, 

i tried today apply to a stream of trade_aggregations however get "failed to get stream message". 

```py

from stellar_sdk import Server
from stellar_sdk import Asset

server = Server(horizon_url="https://horizon.stellar.org")

xlm_native = Asset.native()
usdc_asset = Asset('USDC', 'GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN')

for candle in server.trade_aggregations(base=usdc_asset, counter=xlm_native, resolution=60000).stream():
    print(candle)
```

Error: 

```
fetch https://horizon.stellar.org/trade_aggregations failed with wrong response status: 406
Traceback (most recent call last):
  File "D:\The Algo Hub\candle_stream\candlestream10\lib\site-packages\stellar_sdk\client\requests_client.py", line 171, in stream
    with EventSource(
  File "D:\The Algo Hub\candle_stream\candlestream10\lib\site-packages\requests_sse\client.py", line 164, in __enter__
    self.connect(self._max_connect_retry)
  File "D:\The Algo Hub\candle_stream\candlestream10\lib\site-packages\requests_sse\client.py", line 277, in connect
    raise InvalidStatusCodeError(
requests_sse.client.InvalidStatusCodeError: fetch https://horizon.stellar.org/trade_aggregations failed with wrong response status: 406

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\The Algo Hub\candle_stream\dex\dex_stellar.py", line 33, in <module>
    for candle in server.trade_aggregations(base=usdc_asset, counter=xlm_native, resolution=60000).stream():
  File "D:\The Algo Hub\candle_stream\candlestream10\lib\site-packages\stellar_sdk\client\requests_client.py", line 196, in stream
    query_params["cursor"], "Failed to get stream message."
KeyError: 'cursor'
```

normal call() works normally. 

**What version of dependencies are you using?**
```
annotated-types==0.6.0
certifi==2024.2.2        
cffi==1.16.0
charset-normalizer==3.3.2
idna==3.6
mnemonic==0.20
pycparser==2.21
pydantic==2.6.0
pydantic_core==2.16.1
PyNaCl==1.5.0
requests==2.31.0
requests-sse==0.3.1
stellar-sdk==9.2.0
toml==0.10.2
typing_extensions==4.9.0
urllib3==2.2.0
xdrlib3==0.1.1
```

**Comment by overcat** [comment]
Sorry, this API currently cannot provide streaming.

**Comment by AnimusXCASH** [comment]
Ok, thank you

**Comment by AnimusXCASH** [comment]
@overcat do i close the ticket?

**Comment by overcat** [comment]
We have added some prompts to improve it.
